### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by fahim-7770** [dirtycoder0124/XSS-Automation#5]
Show some error.
![Screenshot 2024-12-27 192133](https://github.com/user-attachments/assets/3d0a3f0e-6ec1-4228-9cdd-69a659fc7ff8)
![Screenshot 2024-12-27 192153](https://github.com/user-attachments/assets/02f25bca-5b54-4899-b229-212c31ae72a3)
![Screenshot 2024-12-27 192212](https://github.com/user-attachments/assets/4d68e4e1-36b9-4348-a274-6595b3a421c9)

**Comment by dirtycoder0124** [comment]
Hi, thank you for the information. I have updated the code. The code was not handling HTTP or https properly in the target domain. Now the script is working fine at my end. Please download the latest script and check.
Thank you

**Comment by Goku4756** [comment]
@dirtycoder0124  still facing the same issue 
Usage: httpx [OPTIONS] URL

Error: No such option: -l  this in the tool
